apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogfrontend
spec:
  replicas: 2
  selector:
    matchLabels:      
      si3mshady: blogfrontend    
  template:
    metadata:
      labels:        
        si3mshady: blogfrontend
    spec:
      containers:        
      - name: blogfrontend
        image: si3mshady/blogsite-fe:2         
        resources:
          requests:
            memory: "250Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
          hostPort: 888
          # http://44.193.88.45:888/register
--- 
apiVersion: v1
kind: Service
metadata: 
  name: blogfrontend

spec: 
  ports: 
    - port: 888
      targetPort: 80  
      nodePort:  30007   
       # http://44.193.88.45:888/register
  selector: 
    si3mshady: blogfrontend
  type: NodePort


  # The unit suffix m stands for “thousandth of a core,” so this resources object specifies that the container process needs