- hosts: sandbox #no communication with remote system for this playbook 
  tasks:  
  
   
  - name: Install aptitude using apt
    become: yes    
    become_user: root  
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    become: yes    
    become_user: root    
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    become: yes    
    become_user: root  
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    become: yes    
    become_user: root  
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    become: yes    
    become_user: root  
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
    become: yes    
    become_user: root  
    pip:
      name: docker

  - name: Install Docker-Compose
    become: yes    
    become_user: root  
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  - name: Install Curl 
    become: yes    
    become_user: root
    apt:
      name: curl   

  - name: Install Zip 
    become: yes    
    become_user: root
    apt:
      name: zip  

  - name: install K3s - Lightweight Kubernetes 
    ansible.builtin.shell:
      cmd: curl -sfL https://get.k3s.io | sh -

  - name: Create a jenkins_home directory if it does not exist
    ansible.builtin.file:
      path: /home/ubuntu/jenkins_home
      state: directory
      mode: '0755'

  - name: Create a directory to store jenkins server backups
    ansible.builtin.file:
      path: /home/ubuntu/jenkins_backup
      state: directory
      mode: '0755'

  - name: Get Custom Jenkins Container       
    docker_container:
      name: jenkins_container
      image: si3mshady/jenkins-iam-root
      ports:
      - "8080:8080"      
      volumes:
        - /home/ubuntu/jenkins_home:/var/jenkins_home